development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pardal_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test: &TEST
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pardal_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

cucumber:
  <<: *TEST

staging:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pardal_staging
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pardal_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

academnew:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: academnew
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
